/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as MarshalAfterPhotoRouteImport } from './routes/marshal.after-photo'
import { Route as MarshalDashboardRouteImport } from './routes/marshal.dashboard'
import { Route as MarshalIncomingJobRouteImport } from './routes/marshal.incoming-job'
import { Route as MarshalJobHistoryRouteImport } from './routes/marshal.job-history'
import { Route as MarshalKycRouteImport } from './routes/marshal.kyc'
import { Route as MarshalNavigateRouteImport } from './routes/marshal.navigate'
import { Route as MarshalOnSiteRouteImport } from './routes/marshal.on-site'
import { Route as MarshalPayoutRouteImport } from './routes/marshal.payout'
import { Route as MarshalProfileRouteImport } from './routes/marshal.profile'
import { Route as MarshalRequestsRouteImport } from './routes/marshal.requests'
import { Route as MarshalResolveRouteImport } from './routes/marshal.resolve'
import { Route as MarshalTrainingRouteImport } from './routes/marshal.training'
import { Route as MarshalWalletRouteImport } from './routes/marshal.wallet'
import { Route as OnboardingRoleSelectRouteImport } from './routes/onboarding.role-select'
import { Route as RequesterActivityRouteImport } from './routes/requester.activity'
import { Route as RequesterHomeRouteImport } from './routes/requester.home'
import { Route as RequesterProfileRouteImport } from './routes/requester.profile'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const MarshalAfterPhotoRoute = MarshalAfterPhotoRouteImport.update({
  id: '/marshal/after-photo',
  path: '/marshal/after-photo',
  getParentRoute: () => rootRouteImport,
} as any)
const MarshalDashboardRoute = MarshalDashboardRouteImport.update({
  id: '/marshal/dashboard',
  path: '/marshal/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MarshalIncomingJobRoute = MarshalIncomingJobRouteImport.update({
  id: '/marshal/incoming-job',
  path: '/marshal/incoming-job',
  getParentRoute: () => rootRouteImport,
} as any)
const MarshalJobHistoryRoute = MarshalJobHistoryRouteImport.update({
  id: '/marshal/job-history',
  path: '/marshal/job-history',
  getParentRoute: () => rootRouteImport,
} as any)
const MarshalKycRoute = MarshalKycRouteImport.update({
  id: '/marshal/kyc',
  path: '/marshal/kyc',
  getParentRoute: () => rootRouteImport,
} as any)
const MarshalNavigateRoute = MarshalNavigateRouteImport.update({
  id: '/marshal/navigate',
  path: '/marshal/navigate',
  getParentRoute: () => rootRouteImport,
} as any)
const MarshalOnSiteRoute = MarshalOnSiteRouteImport.update({
  id: '/marshal/on-site',
  path: '/marshal/on-site',
  getParentRoute: () => rootRouteImport,
} as any)
const MarshalPayoutRoute = MarshalPayoutRouteImport.update({
  id: '/marshal/payout',
  path: '/marshal/payout',
  getParentRoute: () => rootRouteImport,
} as any)
const MarshalProfileRoute = MarshalProfileRouteImport.update({
  id: '/marshal/profile',
  path: '/marshal/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MarshalRequestsRoute = MarshalRequestsRouteImport.update({
  id: '/marshal/requests',
  path: '/marshal/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const MarshalResolveRoute = MarshalResolveRouteImport.update({
  id: '/marshal/resolve',
  path: '/marshal/resolve',
  getParentRoute: () => rootRouteImport,
} as any)
const MarshalTrainingRoute = MarshalTrainingRouteImport.update({
  id: '/marshal/training',
  path: '/marshal/training',
  getParentRoute: () => rootRouteImport,
} as any)
const MarshalWalletRoute = MarshalWalletRouteImport.update({
  id: '/marshal/wallet',
  path: '/marshal/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoleSelectRoute = OnboardingRoleSelectRouteImport.update({
  id: '/role-select',
  path: '/role-select',
  getParentRoute: () => OnboardingRoute,
} as any)
const RequesterActivityRoute = RequesterActivityRouteImport.update({
  id: '/requester/activity',
  path: '/requester/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const RequesterHomeRoute = RequesterHomeRouteImport.update({
  id: '/requester/home',
  path: '/requester/home',
  getParentRoute: () => rootRouteImport,
} as any)
const RequesterProfileRoute = RequesterProfileRouteImport.update({
  id: '/requester/profile',
  path: '/requester/profile',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/marshal/after-photo': typeof MarshalAfterPhotoRoute
  '/marshal/dashboard': typeof MarshalDashboardRoute
  '/marshal/incoming-job': typeof MarshalIncomingJobRoute
  '/marshal/job-history': typeof MarshalJobHistoryRoute
  '/marshal/kyc': typeof MarshalKycRoute
  '/marshal/navigate': typeof MarshalNavigateRoute
  '/marshal/on-site': typeof MarshalOnSiteRoute
  '/marshal/payout': typeof MarshalPayoutRoute
  '/marshal/profile': typeof MarshalProfileRoute
  '/marshal/requests': typeof MarshalRequestsRoute
  '/marshal/resolve': typeof MarshalResolveRoute
  '/marshal/training': typeof MarshalTrainingRoute
  '/marshal/wallet': typeof MarshalWalletRoute
  '/onboarding/role-select': typeof OnboardingRoleSelectRoute
  '/requester/activity': typeof RequesterActivityRoute
  '/requester/home': typeof RequesterHomeRoute
  '/requester/profile': typeof RequesterProfileRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/marshal/after-photo': typeof MarshalAfterPhotoRoute
  '/marshal/dashboard': typeof MarshalDashboardRoute
  '/marshal/incoming-job': typeof MarshalIncomingJobRoute
  '/marshal/job-history': typeof MarshalJobHistoryRoute
  '/marshal/kyc': typeof MarshalKycRoute
  '/marshal/navigate': typeof MarshalNavigateRoute
  '/marshal/on-site': typeof MarshalOnSiteRoute
  '/marshal/payout': typeof MarshalPayoutRoute
  '/marshal/profile': typeof MarshalProfileRoute
  '/marshal/requests': typeof MarshalRequestsRoute
  '/marshal/resolve': typeof MarshalResolveRoute
  '/marshal/training': typeof MarshalTrainingRoute
  '/marshal/wallet': typeof MarshalWalletRoute
  '/onboarding/role-select': typeof OnboardingRoleSelectRoute
  '/requester/activity': typeof RequesterActivityRoute
  '/requester/home': typeof RequesterHomeRoute
  '/requester/profile': typeof RequesterProfileRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/marshal/after-photo': typeof MarshalAfterPhotoRoute
  '/marshal/dashboard': typeof MarshalDashboardRoute
  '/marshal/incoming-job': typeof MarshalIncomingJobRoute
  '/marshal/job-history': typeof MarshalJobHistoryRoute
  '/marshal/kyc': typeof MarshalKycRoute
  '/marshal/navigate': typeof MarshalNavigateRoute
  '/marshal/on-site': typeof MarshalOnSiteRoute
  '/marshal/payout': typeof MarshalPayoutRoute
  '/marshal/profile': typeof MarshalProfileRoute
  '/marshal/requests': typeof MarshalRequestsRoute
  '/marshal/resolve': typeof MarshalResolveRoute
  '/marshal/training': typeof MarshalTrainingRoute
  '/marshal/wallet': typeof MarshalWalletRoute
  '/onboarding/role-select': typeof OnboardingRoleSelectRoute
  '/requester/activity': typeof RequesterActivityRoute
  '/requester/home': typeof RequesterHomeRoute
  '/requester/profile': typeof RequesterProfileRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/onboarding'
    | '/marshal/after-photo'
    | '/marshal/dashboard'
    | '/marshal/incoming-job'
    | '/marshal/job-history'
    | '/marshal/kyc'
    | '/marshal/navigate'
    | '/marshal/on-site'
    | '/marshal/payout'
    | '/marshal/profile'
    | '/marshal/requests'
    | '/marshal/resolve'
    | '/marshal/training'
    | '/marshal/wallet'
    | '/onboarding/role-select'
    | '/requester/activity'
    | '/requester/home'
    | '/requester/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/onboarding'
    | '/marshal/after-photo'
    | '/marshal/dashboard'
    | '/marshal/incoming-job'
    | '/marshal/job-history'
    | '/marshal/kyc'
    | '/marshal/navigate'
    | '/marshal/on-site'
    | '/marshal/payout'
    | '/marshal/profile'
    | '/marshal/requests'
    | '/marshal/resolve'
    | '/marshal/training'
    | '/marshal/wallet'
    | '/onboarding/role-select'
    | '/requester/activity'
    | '/requester/home'
    | '/requester/profile'
  id:
    | '__root__'
    | '/'
    | '/onboarding'
    | '/marshal/after-photo'
    | '/marshal/dashboard'
    | '/marshal/incoming-job'
    | '/marshal/job-history'
    | '/marshal/kyc'
    | '/marshal/navigate'
    | '/marshal/on-site'
    | '/marshal/payout'
    | '/marshal/profile'
    | '/marshal/requests'
    | '/marshal/resolve'
    | '/marshal/training'
    | '/marshal/wallet'
    | '/onboarding/role-select'
    | '/requester/activity'
    | '/requester/home'
    | '/requester/profile'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  MarshalAfterPhotoRoute: typeof MarshalAfterPhotoRoute
  MarshalDashboardRoute: typeof MarshalDashboardRoute
  MarshalIncomingJobRoute: typeof MarshalIncomingJobRoute
  MarshalJobHistoryRoute: typeof MarshalJobHistoryRoute
  MarshalKycRoute: typeof MarshalKycRoute
  MarshalNavigateRoute: typeof MarshalNavigateRoute
  MarshalOnSiteRoute: typeof MarshalOnSiteRoute
  MarshalPayoutRoute: typeof MarshalPayoutRoute
  MarshalProfileRoute: typeof MarshalProfileRoute
  MarshalRequestsRoute: typeof MarshalRequestsRoute
  MarshalResolveRoute: typeof MarshalResolveRoute
  MarshalTrainingRoute: typeof MarshalTrainingRoute
  MarshalWalletRoute: typeof MarshalWalletRoute
  RequesterActivityRoute: typeof RequesterActivityRoute
  RequesterHomeRoute: typeof RequesterHomeRoute
  RequesterProfileRoute: typeof RequesterProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marshal/after-photo': {
      id: '/marshal/after-photo'
      path: '/marshal/after-photo'
      fullPath: '/marshal/after-photo'
      preLoaderRoute: typeof MarshalAfterPhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marshal/dashboard': {
      id: '/marshal/dashboard'
      path: '/marshal/dashboard'
      fullPath: '/marshal/dashboard'
      preLoaderRoute: typeof MarshalDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marshal/incoming-job': {
      id: '/marshal/incoming-job'
      path: '/marshal/incoming-job'
      fullPath: '/marshal/incoming-job'
      preLoaderRoute: typeof MarshalIncomingJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marshal/job-history': {
      id: '/marshal/job-history'
      path: '/marshal/job-history'
      fullPath: '/marshal/job-history'
      preLoaderRoute: typeof MarshalJobHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marshal/kyc': {
      id: '/marshal/kyc'
      path: '/marshal/kyc'
      fullPath: '/marshal/kyc'
      preLoaderRoute: typeof MarshalKycRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marshal/navigate': {
      id: '/marshal/navigate'
      path: '/marshal/navigate'
      fullPath: '/marshal/navigate'
      preLoaderRoute: typeof MarshalNavigateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marshal/on-site': {
      id: '/marshal/on-site'
      path: '/marshal/on-site'
      fullPath: '/marshal/on-site'
      preLoaderRoute: typeof MarshalOnSiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marshal/payout': {
      id: '/marshal/payout'
      path: '/marshal/payout'
      fullPath: '/marshal/payout'
      preLoaderRoute: typeof MarshalPayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marshal/profile': {
      id: '/marshal/profile'
      path: '/marshal/profile'
      fullPath: '/marshal/profile'
      preLoaderRoute: typeof MarshalProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marshal/requests': {
      id: '/marshal/requests'
      path: '/marshal/requests'
      fullPath: '/marshal/requests'
      preLoaderRoute: typeof MarshalRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marshal/resolve': {
      id: '/marshal/resolve'
      path: '/marshal/resolve'
      fullPath: '/marshal/resolve'
      preLoaderRoute: typeof MarshalResolveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marshal/training': {
      id: '/marshal/training'
      path: '/marshal/training'
      fullPath: '/marshal/training'
      preLoaderRoute: typeof MarshalTrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marshal/wallet': {
      id: '/marshal/wallet'
      path: '/marshal/wallet'
      fullPath: '/marshal/wallet'
      preLoaderRoute: typeof MarshalWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/role-select': {
      id: '/onboarding/role-select'
      path: '/role-select'
      fullPath: '/onboarding/role-select'
      preLoaderRoute: typeof OnboardingRoleSelectRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/requester/activity': {
      id: '/requester/activity'
      path: '/requester/activity'
      fullPath: '/requester/activity'
      preLoaderRoute: typeof RequesterActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requester/home': {
      id: '/requester/home'
      path: '/requester/home'
      fullPath: '/requester/home'
      preLoaderRoute: typeof RequesterHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/requester/profile': {
      id: '/requester/profile'
      path: '/requester/profile'
      fullPath: '/requester/profile'
      preLoaderRoute: typeof RequesterProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface OnboardingRouteChildren {
  OnboardingRoleSelectRoute: typeof OnboardingRoleSelectRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingRoleSelectRoute: OnboardingRoleSelectRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  MarshalAfterPhotoRoute: MarshalAfterPhotoRoute,
  MarshalDashboardRoute: MarshalDashboardRoute,
  MarshalIncomingJobRoute: MarshalIncomingJobRoute,
  MarshalJobHistoryRoute: MarshalJobHistoryRoute,
  MarshalKycRoute: MarshalKycRoute,
  MarshalNavigateRoute: MarshalNavigateRoute,
  MarshalOnSiteRoute: MarshalOnSiteRoute,
  MarshalPayoutRoute: MarshalPayoutRoute,
  MarshalProfileRoute: MarshalProfileRoute,
  MarshalRequestsRoute: MarshalRequestsRoute,
  MarshalResolveRoute: MarshalResolveRoute,
  MarshalTrainingRoute: MarshalTrainingRoute,
  MarshalWalletRoute: MarshalWalletRoute,
  RequesterActivityRoute: RequesterActivityRoute,
  RequesterHomeRoute: RequesterHomeRoute,
  RequesterProfileRoute: RequesterProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
